paths:
    cache: %app%/cache
    config: %app%/config
    database: %app%/database
    extensions: %site%/extensions
    extensions_config: %config%/extensions
    web: %site%/public
    files: %web%/files
    themes: %web%/theme
    bolt_assets: %web%/bolt-public
